# Generated by Django 3.2.7 on 2021-09-28 09:00

import banjo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banjo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banjo.model')),
                ('question', banjo.models.StringField(default='')),
                ('answer', banjo.models.StringField(default='')),
                ('guesses', banjo.models.IntegerField(default=0)),
                ('correct', banjo.models.IntegerField(default=0)),
            ],
            bases=('banjo.model',),
        ),
    ]
